<template>
    <v-row class="card-container">
        <v-col cols="12" align-self="start">
            <v-container>
                <v-row class="ma-0 mt-3">
                    <label class="card-info-title">Supply Capital, Earn Premiums. Yield by providing insurance with OVN</label>
                </v-row>

                <v-row class="ma-0 mt-8">
                    <label class="card-info">
                        Overnight introduces Overnight Insurance Vault (1 per chain), where OVN holders will be able to
                        stake OVN in exchange for insurance premiums (1 INS = 1 OVN). Staked OVN will receive a part of
                        the yield generated by the insured strategies (not all strategies will be insured) and in case
                        the strategy is unprofitable on a specific day the entire incurred loss. During profitable days
                        excess yield generated by the strategies will accrue to the Insurance Vault and will be used to
                        buy OVN off the market and add to the vault; In case of a loss, the opposite would happen. As
                        these vaults won’t be immediately redeemable, stakers will have a vested interest to support
                        strategies with optimal risk reward upfront.

                        <br/>
                        <br/>
                        Insurance is made to protect collateral of our rebase tokens from minor losses. First insurance is on Optimism, Base is the next chain. We only insure collateral of our products on chains where the risks are
                        acceptable to us.
                    </label>
                </v-row>

                <v-row class="ma-0" :class="$wu.isFull() ? 'mt-12' : ($wu.isTablet() ? 'mt-8' : 'mt-5')" align="start" justify="center">
                    <img class="insurance-about-img img-wide" :src="require('@/assets/insurance/insurance_ovn_about_horizontal.svg')"/>
                    <img class="insurance-about-img img-narrow" :src="require('@/assets/insurance/insurance_ovn_about_vertical.svg')"/>
                </v-row>
            </v-container>
        </v-col>

        <resize-observer @notify="$forceUpdate()"/>
    </v-row>
</template>

<script>

export default {
    name: "InsuranceInfoCard",

    components: {
    },

    props: {},

    computed: {
    },

    data: () => ({
    }),

    watch: {
    },

    created() {
    },

    methods: {
    }
};
</script>

<style scoped>

/* mobile */
@media only screen and (max-width: 960px) {
    .card-info {
        font-style: normal;
        font-weight: 300;
        font-size: 14px;
        line-height: 22px;
    }

    .card-info-title {
        font-style: normal;
        font-weight: 400;
        font-size: 20px;
        line-height: 28px;
    }

    .card-container {

    }
}

/* tablet */
@media only screen and (min-width: 960px) and (max-width: 1400px) {
    .card-info {
        font-style: normal;
        font-weight: 300;
        font-size: 16px;
        line-height: 22px;
    }

    .card-info-title {
        font-style: normal;
        font-weight: 400;
        font-size: 22px;
        line-height: 32px;
    }

    .card-container {
        max-height: 100%;
    }
}

/* full */
@media only screen and (min-width: 1400px) {
    .card-info {
        font-style: normal;
        font-weight: 300;
        font-size: 16px;
        line-height: 24px;
    }

    .card-info-title {
        font-style: normal;
        font-weight: 400;
        font-size: 24px;
        line-height: 36px;
    }

    .card-container {
        max-width: 920px;
    }
}

@media only screen and (min-width: 1300px) {
    .card-info {
        font-style: normal;
        font-weight: 300;
        font-size: 16px;
        line-height: 24px;
    }

    .card-info-title {
        font-style: normal;
        font-weight: 400;
        font-size: 22px;
        line-height: 36px;
    }

    .card-container {
        max-width: 920px;
    }
}

@media only screen and (max-width: 1260px) {
    .img-wide {
        display: none;
    }
}

@media only screen and (min-width: 1260px) {
    .img-narrow {
        display: none;
    }
}

.card-container {
    background: var(--secondary) !important;
    border-radius: 15px !important;
    height: 100% !important;
}

.card-info {
    font-feature-settings: 'pnum' on, 'lnum' on;
    color: var(--main-gray-text);
}

.card-info-title {
    font-feature-settings: 'liga' off;
    color: var(--main-gray-text);
}

.insurance-about-img {
    max-width: 100% !important;
}
</style>
